name: Deploy Sphinx documentation to Pages
on:
  push:
    branches: [main] # branch to trigger deployment
  pull_request:
    branches: [gh-pages]

jobs:
  pages:
    permissions:
      contents: write
    runs-on: self-hosted
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme

    - name: make the sphinx docs
      run: |
        make -C docs clean
        make -C docs html
    - name: Deplay to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
