name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment
  pull_request:
    branches: [gh-pages]

jobs:
  pages:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme

    - name: make the sphinx docs
      run: |
        make -C docs clean
        make -C docs html

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/build/html
        git init
        git checkout -b gh-pages
        touch .nojekyll
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global --add safe.directory /github/workspace/docs/build/html
        git commit -m "deploy"
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
